[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/Apple System Colors.toml"]

[window]
opacity = 0.87
blur = false
decorations = "Full"
startup_mode = "Windowed"
dynamic_padding = true
dynamic_title = false
resize_increments = true
option_as_alt = "OnlyRight"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
italic = { family = "RobotoMono Nerd Font", style = "Italic" }
bold_italic = { family = "RobotoMono Nerd Font", style = "Bold Italic" }
size = 12.25

[bell]
animation = "Ease"
duration = 200
color = "#34206b"
command = { program = "osascript", args = ["-e", "beep"] }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  # Переход вперёд по словам (Option + →)
  { key = "Right", mods = "Alt", chars = "\u001bf" },

  # Переход назад по словам (Option + ←)
  { key = "Left", mods = "Alt", chars = "\u001bb" },

  # Удаление слова перед курсором (Option + Backspace)
  { key = "Backspace", mods = "Alt", chars = "\u001b\u007f" },

  # Создание нового окна (Control + Shift + N)
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
